spring.application.name=spring-ai-basic-chat-service

spring.config.import=optional:file:.env[.properties]

spring.ai.google.genai.api-key=${gemini_api_key}

spring.ai.google.genai.chat.model=gemini-3.1-flash-lite
spring.ai.google.genai.chat.temperature=0.7

spring.ai.google.genai.embedding.api-key=${gemini_api_key}
spring.ai.google.genai.embedding.text.model=gemini-embedding-2